### ISSUE TITLE
Please check and (dis)agree on colors for comparisonplot GARCH and RealGARCH  model with ratio

### ISSUE THREAD

**Issue by LuukOudshoorn25** [LuukOudshoorn25/HighFrequencyTrading#17]
Currently fig 11 in paper.

**Comment by melissahml** [comment]
Wat mij betreft prima!
Als je twijfelt heb ik nog een suggestie: zie figure 12 nu, GARCH zwart en RGARCH tomato.
De ratio zou ik wel sws die dodgerblue houden want anders krijg je een zwarte lijn over die zwarte stippellijn heen, wat me niet nice lijkt.

**Comment by simondonkervanheel** [comment]
Ik zou de kleur van de ratio veranderen. Nu lijkt het op het eerste aanzicht een beetje alsof die ratio de GARCH is, terwijl het juist de ratio van de RGARCH over de GARCH is. Welke kleur precies maakt niet heel veel uit, zolang het maar anders is dan dodgerblue of tomato.

**Comment by melissahml** [comment]
dan zou ik dus juist de GARCH veranderen naar zwart! dan komt t ook overeen met bijv fig 12, en zijn die 2 anders

**Comment by simondonkervanheel** [comment]
Ja dat is perfect
